Repository Trinity5757/GameDesign, pull requests merged in 2024-11, with the labels that each got.

#24 Finished Pause Menu and Started the Code for the minigames.
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/settings.json
  Assets/Audio/sad-meow-song.mp3
  Assets/Audio/sad-meow-song.mp3.meta
  Assets/Scenes/PauseMenu.unity
  Assets/Scenes/PauseMenu.unity.meta
  Assets/Scenes/WireMinigame.unity
  Assets/Scenes/WireMinigame.unity.meta
  Assets/Scripts/AudioManager.cs
  Assets/Scripts/AudioManager.cs.meta
  Assets/Scripts/PauseMenuScript.cs
  Assets/Scripts/PauseMenuScript.cs.meta
  Assets/Scripts/Timer.cs
  Assets/Scripts/Timer.cs.meta
  Assets/Scripts/WireConnection.cs
  Assets/Scripts/WireConnection.cs.meta
  Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF.asset
  ProjectSettings/ProjectSettings.asset
Labels: MVP

#36 Re-import of Bench, chair, and table
  .gitignore
  Assets/Models/bench.obj
  Assets/Models/bench.obj.meta
  Assets/Models/busStop.blend
  Assets/Models/busStop.blend.meta
  Assets/Models/table.obj
  Assets/Models/table.obj.meta
  Assets/Prefabs/Models.meta
  Assets/Prefabs/Models/bench.prefab
  Assets/Prefabs/Models/bench.prefab.meta
  Assets/Prefabs/Models/chair.prefab
  Assets/Prefabs/Models/chair.prefab.meta
  Assets/Prefabs/Models/table.prefab
  Assets/Prefabs/Models/table.prefab.meta
  Assets/Scenes/Models.unity
  Assets/Scenes/NpcDialogue.unity
Labels: MVP

#37 Update README.md
  README.md
Labels: documentation

#48 testing blocked out scene made in blender
  Assets/Models/test env.obj
  Assets/Models/test env.obj.meta
  Assets/Scenes/test import env.unity
  Assets/Scenes/test import env.unity.meta
Labels: Juice

#47 Added Materials, persistent storage, inventory, save file, and maybe more.
  Assets/Prefabs/Materials.meta
  Assets/Prefabs/Materials/Metal.mat
  Assets/Prefabs/Materials/Metal.mat.meta
  Assets/Scenes/SaveScene.unity
  Assets/Scenes/SaveScene.unity.meta
  Assets/Scripts/GameManager.cs
  Assets/Scripts/Inventory.cs
  Assets/Scripts/Inventory.cs.meta
  Assets/Scripts/MaterialData.cs
  Assets/Scripts/MaterialData.cs.meta
  Assets/Scripts/ResourceObject.cs
  Assets/Scripts/ResourceObject.cs.meta
  Assets/Scripts/SaveData.cs
  Assets/Scripts/SaveData.cs.meta
Labels: MVP

#49 Finished Minigame 1
  Assets/Materials/WireMaterial.mat
  Assets/Materials/WireMaterial.mat.meta
  Assets/Scenes/WireMinigame.unity
  Assets/Scripts/UnpoweredWireBehavior.cs
  Assets/Scripts/UnpoweredWireBehavior.cs.meta
  Assets/Scripts/UnpoweredWireStats.cs
  Assets/Scripts/UnpoweredWireStats.cs.meta
  Assets/Scripts/Wire.cs
  Assets/Scripts/Wire.cs.meta
  Assets/Scripts/WireConnection.cs
  Assets/Scripts/WireStats.cs
  Assets/Scripts/WireTask.cs
  Assets/Scripts/WireTask.cs.meta
Labels: MVP
