Repository Trinity5757/GameDesign, pull requests merged in 2024-12, with the labels that each got.

#50 Added Material Node Prefabs
  Assets/Prefabs/Material Nodes.meta
  Assets/Prefabs/Material Nodes/Glass Node.prefab
  Assets/Prefabs/Material Nodes/Glass Node.prefab.meta
  Assets/Prefabs/Material Nodes/Metal Node.prefab
  Assets/Prefabs/Material Nodes/Metal Node.prefab.meta
  Assets/Prefabs/Material Nodes/Organic Node.prefab
  Assets/Prefabs/Material Nodes/Organic Node.prefab.meta
  Assets/Prefabs/Material Nodes/Plastic Node.prefab
  Assets/Prefabs/Material Nodes/Plastic Node.prefab.meta
  Assets/Prefabs/Materials/Glass.mat
  Assets/Prefabs/Materials/Glass.mat.meta
  Assets/Prefabs/Materials/Organic.mat
  Assets/Prefabs/Materials/Organic.mat.meta
  Assets/Prefabs/Materials/Plastic.mat
  Assets/Prefabs/Materials/Plastic.mat.meta
  Assets/Scenes/SaveScene.unity
Labels: Juice

#55 Enemy Health/Bow and Arrow added
  Assets/AddressableAssetsData/ProfileDataSourceSettings.asset
  Assets/AddressableAssetsData/ProfileDataSourceSettings.asset.meta
  Assets/Localization/UI Shared Data.asset
  Assets/Localization/UI_en.asset
  Assets/Localization/UI_es.asset
  Assets/Prefabs/Arrow.prefab
  Assets/Prefabs/Arrow.prefab.meta
  Assets/Prefabs/Pause Menu Canvas.prefab
  Assets/Prefabs/Pause Menu Canvas.prefab.meta
  Assets/Prefabs/enemy.prefab
  Assets/Scenes/Menu.unity
  Assets/Scenes/PauseMenu.unity
  Assets/Scenes/SaveScene.unity
  Assets/Scripts/Arrow.cs
  Assets/Scripts/Arrow.cs.meta
  Assets/Scripts/Bow.cs
  Assets/Scripts/Bow.cs.meta
  Assets/Scripts/Enemy.cs
  Assets/Scripts/Enemy.cs.meta
  Assets/Scripts/Inventory.cs
  Assets/Scripts/PauseMenuScript.cs
  Assets/Settings/Universal Renderer.asset
  Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Anton SDF.asset
  Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Bangers SDF.asset
  Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Electronic Highway Sign SDF.asset
  Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Oswald Bold SDF.asset
  Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Roboto-Bold SDF.asset
  Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
  Assets/Thaleah_PixelFont.meta
  Assets/Thaleah_PixelFont/Materials.meta
  Assets/Thaleah_PixelFont/Materials/ThaleahFat.mat
  Assets/Thaleah_PixelFont/Materials/ThaleahFat.mat.meta
  Assets/Thaleah_PixelFont/Materials/ThaleahFat.png
  Assets/Thaleah_PixelFont/Materials/ThaleahFat.png.meta
  Assets/Thaleah_PixelFont/Materials/ThaleahFat_TTF SDF.asset
  Assets/Thaleah_PixelFont/Materials/ThaleahFat_TTF SDF.asset.meta
  Assets/Thaleah_PixelFont/Materials/ThaleahFat_TTF.ttf
  Assets/Thaleah_PixelFont/Materials/ThaleahFat_TTF.ttf.meta
  Assets/Thaleah_PixelFont/Materials/Thaleah_DemoBackground.png
  Assets/Thaleah_PixelFont/Materials/Thaleah_DemoBackground.png.meta
  Assets/Thaleah_PixelFont/ThaleahFat.fontsettings
  Assets/Thaleah_PixelFont/ThaleahFat.fontsettings.meta
  Assets/Thaleah_PixelFont/Thaleah_Readme.pdf
  Assets/Thaleah_PixelFont/Thaleah_Readme.pdf.meta
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/ScriptableBuildPipeline.json
  ProjectSettings/TagManager.asset
Labels: MVP

#56 Minigame #2 and MiniGame #3
  Assets/Scenes/CastingMiniGame.unity
  Assets/Scenes/CastingMiniGame.unity.meta
  Assets/Scenes/PouringMinigame.unity
  Assets/Scripts/BlowingBubble.cs
  Assets/Scripts/CastingScript.cs
  Assets/Scripts/CastingScript.cs.meta
  Assets/Scripts/PopUp.cs
  Assets/Scripts/PopUp.cs.meta
Labels: bug

#59 Bubble Minigame: Gameplay fixes
  Assets/Scripts/BlowingBubble.cs
Labels: MVP

#61 A shit ton of things
  Assets/Prefabs/Materials/Glass UI.mat
  Assets/Prefabs/Materials/Glass UI.mat.meta
  Assets/Prefabs/Materials/Metal UI.mat
  Assets/Prefabs/Materials/Metal UI.mat.meta
  Assets/Prefabs/Materials/Organic UI.mat
  Assets/Prefabs/Materials/Organic UI.mat.meta
  Assets/Prefabs/Materials/Plastic UI.mat
  Assets/Prefabs/Materials/Plastic UI.mat.meta
  Assets/Prefabs/Pause Menu Canvas.prefab
  Assets/Prefabs/Wire Mini Game Prefab.prefab
  Assets/Prefabs/Wire Mini Game Prefab.prefab.meta
  Assets/Scenes/Nathan's Forest.unity
  Assets/Scenes/Nathan's Forest.unity.meta
  Assets/Scenes/PouringMinigame.unity
  Assets/Scenes/SaveScene.unity
  Assets/Scenes/WireMinigame.unity
  Assets/Scripts/Interactor.cs
  Assets/Scripts/MiniGame.cs
  Assets/Scripts/MiniGame.cs.meta
  Assets/Scripts/MiniGameManager.cs
  Assets/Scripts/MiniGameManager.cs.meta
  Assets/Scripts/Wire.cs
  Assets/Scripts/WireTask.cs
  Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Electronic Highway Sign SDF.asset
  Assets/Thaleah_PixelFont/Materials/ThaleahFat_TTF SDF.asset
  ProjectSettings/TagManager.asset
Labels: MVP

#67 Integration of bubble minigames + minigame+manager bug fixes
  Assets/Prefabs/Bubble Game.prefab
  Assets/Prefabs/Bubble Game.prefab.meta
  Assets/Prefabs/Wire Mini Game Prefab.prefab
  Assets/Prefabs/WorkBench.prefab
  Assets/Prefabs/WorkBench.prefab.meta
  Assets/Scenes/Nathan's Forest.unity
  Assets/Scenes/PouringMinigame.unity
  Assets/Scripts/BlowingBubble.cs
  Assets/Scripts/MiniGame.cs
  Assets/Scripts/MiniGameManager.cs
  Assets/Scripts/WireTask.cs
  Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Electronic Highway Sign SDF.asset
  ProjectSettings/EditorBuildSettings.asset
Labels: MVP

#65 Camera Manager
  Assets/AddressableAssetsData/AssetGroups/Default Local Group.asset
  Assets/Audio/sad-meow-song.mp3
  Assets/Scenes/CastingMiniGame.unity
  Assets/Scenes/Nathan's Forest.unity
  Assets/Scripts/AudioManager.cs
  Assets/Scripts/BlowingBubble.cs
  Assets/Scripts/HUDController.cs
  Assets/Scripts/MiniGameManager.cs
  Assets/Scripts/PauseMenuScript.cs
  Assets/Scripts/SecondaryCamera.cs
  Assets/Scripts/SecondaryCamera.cs.meta
  Assets/Scripts/Wire.cs
  Assets/Scripts/WireTask.cs
  Assets/motivational-background-corporate-city-273359.mp3
  Assets/motivational-background-corporate-city-273359.mp3.meta
  Packages/manifest.json
  Packages/packages-lock.json
Labels: MVP, Urgent

#69 Audio Completed
  Assets/AddressableAssetsData/AssetGroups/Default Local Group.asset
  Assets/CasualGameBGM05.meta
  Assets/CasualGameBGM05/BGM_02.wav
  Assets/CasualGameBGM05/BGM_02.wav.meta
  Assets/Leohpaz.meta
  Assets/Leohpaz/RPG_Essentials_Free.meta
  Assets/Leohpaz/RPG_Essentials_Free/10_Battle_SFX.meta
  Assets/Leohpaz/RPG_Essentials_Free/10_Battle_SFX/22_Slash_04.wav
  Assets/Leohpaz/RPG_Essentials_Free/10_Battle_SFX/22_Slash_04.wav.meta
  Assets/Leohpaz/RPG_Essentials_Free/10_UI_Menu_SFX.meta
  Assets/Leohpaz/RPG_Essentials_Free/10_UI_Menu_SFX/013_Confirm_03.wav
  Assets/Leohpaz/RPG_Essentials_Free/10_UI_Menu_SFX/013_Confirm_03.wav.meta
  Assets/Leohpaz/RPG_Essentials_Free/10_UI_Menu_SFX/092_Pause_04.wav
  Assets/Leohpaz/RPG_Essentials_Free/10_UI_Menu_SFX/092_Pause_04.wav.meta
  Assets/Leohpaz/RPG_Essentials_Free/10_UI_Menu_SFX/098_Unpause_04.wav
  Assets/Leohpaz/RPG_Essentials_Free/10_UI_Menu_SFX/098_Unpause_04.wav.meta
  Assets/Leohpaz/RPG_Essentials_Free/12_Player_Movement_SFX.meta
  Assets/Leohpaz/RPG_Essentials_Free/12_Player_Movement_SFX/61_Hit_03.wav
  Assets/Leohpaz/RPG_Essentials_Free/12_Player_Movement_SFX/61_Hit_03.wav.meta
  Assets/Scenes/Nathan's Forest.unity
  Assets/Scripts/AudioManager.cs
  Assets/Scripts/Bow.cs
  Assets/Scripts/Enemy.cs
  Assets/Scripts/MiniGameManager.cs
Labels: Juice
